# Generated by Django 3.2.13 on 2022-08-30 16:49

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalCampVenues',
            new_name='MedicalCampVenue',
        ),
        migrations.AlterModelOptions(
            name='medicinecategory',
            options={'verbose_name_plural': 'Medicine Categories'},
        ),
    ]
