# Generated by Django 3.2.13 on 2022-08-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220830_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='formulation',
            field=models.CharField(default='', max_length=4000),
            preserve_default=False,
        ),
    ]
