# Generated by Django 3.2.13 on 2022-08-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_medicine_formulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
