# Generated by Django 4.2.11 on 2024-07-16 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_medicine_expiry_date_vitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='vitals',
            options={'verbose_name_plural': 'Vitals'},
        ),
        migrations.CreateModel(
            name='TestIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicalcamp')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicaltest')),
            ],
        ),
    ]
