# Generated by Django 6.0.4 on 2026-05-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_medicaltest_alter_vitals_options_testissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(unique=True)),
                ('patient_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_addr', models.CharField(blank=True, max_length=4000, null=True)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('camp_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient_details',
            },
        ),
    ]
