# Generated by Django 6.0.4 on 2026-05-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='camp_no',
            new_name='camp_session',
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
