# Generated by Django 6.0.4 on 2026-05-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_camp_no_patient_camp_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='uqid',
            field=models.IntegerField(unique=True),
        ),
    ]
