# Generated by Django 6.0.4 on 2026-05-06 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_medicine_uqid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampWiseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uqid', models.IntegerField(unique=True)),
                ('medication', models.CharField(max_length=2000)),
                ('total_stock', models.IntegerField()),
                ('camp_stock', models.IntegerField(default=0)),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camp_wise_info', to='inventory.medicine')),
            ],
        ),
    ]
