# Generated by Django 6.0.4 on 2026-05-06 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_campwisestock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campwisestock',
            name='id',
        ),
        migrations.AlterField(
            model_name='campwisestock',
            name='medicine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='camp_wise_info', serialize=False, to='inventory.medicine'),
        ),
    ]
