# Generated by Django 6.0.4 on 2026-05-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_campwisestock_id_alter_campwisestock_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampWiseStock',
        ),
    ]
