# Generated by Django 6.0.4 on 2026-05-07 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_delete_campwisestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampWiseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_stock', models.IntegerField(default=0)),
                ('used_stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_stocks', to='inventory.medicalcamp')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_stocks', to='inventory.medicine')),
            ],
            options={
                'unique_together': {('camp', 'medicine')},
            },
        ),
    ]
