# Generated by Django 6.0.4 on 2026-05-07 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_vitals_date_vitals_diagnosis_vitals_dr_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitals',
            name='date',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='dr_id',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='dr_name',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='e_no',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='height',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='last_food_time',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='pulse',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='rbs',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='time',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='weight',
        ),
        migrations.AlterField(
            model_name='vitals',
            name='blood_pressure',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitals',
            name='glucose',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitals',
            name='haemoglobin',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('e_no', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=100, null=True)),
                ('pulse', models.CharField(blank=True, max_length=100, null=True)),
                ('glucose', models.CharField(blank=True, max_length=100, null=True)),
                ('rbs', models.CharField(blank=True, max_length=100, null=True)),
                ('haemoglobin', models.CharField(blank=True, max_length=100, null=True)),
                ('last_food_time', models.CharField(blank=True, max_length=200, null=True)),
                ('dr_name', models.CharField(blank=True, max_length=500, null=True)),
                ('dr_id', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicalcamp')),
            ],
            options={
                'verbose_name_plural': 'Patient Vitals',
                'db_table': 'patient_vitals',
            },
        ),
    ]
