# Generated by Django 6.0.4 on 2026-05-07 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_vitals_date_remove_vitals_diagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVitalsMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('days', models.IntegerField(default=0)),
                ('morning', models.IntegerField(default=0)),
                ('afternoon', models.IntegerField(default=0)),
                ('night', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicine')),
                ('vitals_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='inventory.patientvitals')),
            ],
        ),
    ]
