# Generated by Django 6.0.4 on 2026-05-07 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_patientvitalsmedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvitals',
            name='afternoon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientvitals',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientvitals',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.medicine'),
        ),
        migrations.AddField(
            model_name='patientvitals',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientvitals',
            name='morning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientvitals',
            name='night',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientvitals',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientvitals',
            name='strength',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PatientVitalsMedicine',
        ),
    ]
