# Generated by Django 6.0.4 on 2026-05-07 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_patientvitals_afternoon_patientvitals_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvitals',
            name='afternoon',
        ),
        migrations.RemoveField(
            model_name='patientvitals',
            name='days',
        ),
        migrations.RemoveField(
            model_name='patientvitals',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='patientvitals',
            name='medicine_name',
        ),
        migrations.RemoveField(
            model_name='patientvitals',
            name='morning',
        ),
        migrations.RemoveField(
            model_name='patientvitals',
            name='night',
        ),
        migrations.RemoveField(
            model_name='patientvitals',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='patientvitals',
            name='strength',
        ),
        migrations.AddField(
            model_name='issue',
            name='afternoon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='morning',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='night',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='strength',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='vitals_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_medicines', to='inventory.patientvitals'),
        ),
    ]
