# Generated by Django 6.0.4 on 2026-05-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_patientvitals_afternoon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcamp',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
