# Generated by Django 6.0.4 on 2026-05-08 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_medicalcamp_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issue',
            new_name='PatientMedicineIssue',
        ),
    ]
