# Generated by Django 6.0.5 on 2026-05-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_rename_issue_patientmedicineissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltest',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='patient_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='test_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
