# Generated by Django 6.0.5 on 2026-05-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_medicaltest_actual_cost_medicaltest_patient_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testissue',
            name='records_issued',
            field=models.BooleanField(default=False),
        ),
    ]
