# Generated by Django 6.0.5 on 2026-05-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_testissue_records_issued'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testissue',
            old_name='records_issued',
            new_name='reports_issued',
        ),
    ]
