# Generated by Django 6.0.5 on 2026-05-09 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_rename_records_issued_testissue_reports_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.medicinecategory'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='formulation',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
