# Generated by Django 6.0.5 on 2026-05-09 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_medicine_category_alter_medicine_formulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campwisestock',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_stocks', to='inventory.medicine', to_field='uqid'),
        ),
    ]
