# Generated by Django 6.0.5 on 2026-05-09 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_campwisestock_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicineissue',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicine', to_field='uqid'),
        ),
    ]
