# Generated by Django 6.0.5 on 2026-05-09 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_patientmedicineissue_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campwisestock',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_stocks', to='inventory.medicalcamp', to_field='number'),
        ),
        migrations.AlterField(
            model_name='patientmedicineissue',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicalcamp', to_field='number'),
        ),
        migrations.AlterField(
            model_name='patientvitals',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicalcamp', to_field='number'),
        ),
        migrations.AlterField(
            model_name='testissue',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicalcamp', to_field='number'),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicalcamp', to_field='number'),
        ),
    ]
