# Generated by Django 6.0.5 on 2026-05-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_campwisestock_camp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='company_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
